config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :category
  has_one_attached :image
  attribute :new_image

  validates :title, presence: true, length: { maximum: 50 }
  validates :price, presence: true,
    numericality: { 
      only_integer: true,
      greater_than: 1
    }
  validates :publish_date, presence: true
  validates :description, presence: true, length: { maximum: 1000 }

  before_save do
    self.image = new_image if new_image
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  protected 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nick_name, :avatar])
  end

end

app/controllers/books_controller.rb
# app/controllers/books_controller.rb

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end 
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: "書籍を登録しました。"
    else
      render :new
    end
  end 

  def show

  end

  def edit

  end
  
  def update

    if @book.update(book_params)
      redirect_to @book, notice: "書籍を更新しました。"
    else
      render :edit
    end
  end

  def destroy

    @book.destroy
    redirect_to books_path, notice: "書籍を削除しました。"
  end

  def index
    @books = Book.all
  end

  private 
  def book_params
    params.require(:book).permit(:title, :price, :publish_date, :description, :new_image, :category_id)
  end

  def set_book
    @book = Book.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def show_book_image(book)
    if book.image.attached?
      image_tag book.image.variant(resize: "300x300"), class: "img-thumbnail"
    else
      image_tag "no_image.png", class: "img-thumbnail"
    end
  end
end

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |form| %>
  <%= render "shared/errors", obj: book %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :new_image %><br>
    <%= form.file_field :new_image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %><br>
    <%= form.number_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :publish_date %><br>
    <%= form.date_field :publish_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name , { include_blank: t(".include_blank") },  { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <%= render 'form', book: @book %>
</div>

app/views/books/index.html.erb
<% @books.each do |book| %>
  <div class="col-lg-3 col-md-4  col-sm-6 mb-3">
    <%= show_book_image book %>
    <h4 class="mt-2"><%= link_to book.title, book_path(book) %></h4>
    <div><%= t(".price_yen", price: (number_with_delimiter book.price)) %></div>
    <p><%= truncate(book.description, length: 20) %></p>
  </div>
<% end %>

app/views/books/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <div class="row">
    <div class="col-md-4 mb-4">
      <%= show_book_image(@book) %>
    </div>
    <div class="col-md-8">
      <h2><%= @book.title %></h2>
      <ul>
        <li><b><%= t ".price" %>: </b><%= t(".price_yen", price: (number_with_delimiter @book.price)) %></li>
        <li><b><%= t ".publish_date" %>: </b><%= @book.publish_date %></li>
        <li><b><%= t ".category" %>: </b><%= @book.category.try(:name) %></li>
      </ul>
    </div>
  </div>
  <hr>
  <h4><%= t ".description" %></h4>
  <%= simple_format @book.description %>
  <%= link_to t(".edit"), edit_book_path(@book), class: "btn btn-primary" %>
  <%= button_tag t(".delete"), class: "btn btn-warning", data: { toggle: "modal", target: "#delete-book" } %>
  <%= link_to t(".return"), books_path, class: "btn btn-secondary" %>
</div>

<div class="modal fade" id="delete-book">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t(".modal_title") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(".question_book", book: @book.title) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".chancel") %></button>
        <%= link_to t(".delete_action"), book_path(@book), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookShelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to t(".title"), root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to t(".home"), root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".new_book"), new_book_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to t(".edit_registration"), edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t(".log_out"), destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t(".new_registration"), new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t(".log_in"), new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>